In [1]:
import numpy as np
import pandas as pd
import pyomo.environ as pyo
import importlib.resources
import sys
import os
import json
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from utils import read_gmlc_gen
import matplotlib.pyplot as plt

## Read gen.csv

In [7]:
csv_path = os.path.join(os.getcwd(), '..', 'Data', 'gen.csv')
json_path = os.path.join(os.getcwd(), '..', 'Data', 'rtsgmle_gen_linear_cost_curve.json')
df = read_gmlc_gen(csv_path)
with open(json_path, 'rb') as f:
    gen_param_dict = json.load(f)

bus_path = os.path.join(os.getcwd(), "..", "Data", "bus.csv")
df_bus = pd.read_csv(bus_path)

In [8]:
# extract the CT, CC, STEAM, WIND, PV units
target_fossil_gen = []
target_renew_gen = []
target_special_gen = []
for idx, row in df.iterrows():
    if row['Unit Type'] in ['CT', 'CC', 'STEAM']:
        target_fossil_gen.append(row)
    if row['Unit Type'] in ['PV', 'WIND', 'HYDRO', 'RTPV']:
        target_renew_gen.append(row)
    if row['Unit Type'] in ['CSP', 'NUCLEAR']:
        target_special_gen.append(row)
df_fossil = pd.DataFrame(target_fossil_gen)
df_renew = pd.DataFrame(target_renew_gen)
df_special = pd.DataFrame(target_special_gen)

In [25]:
df_fossil

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,Category,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Emissions N2O Lbs/MMBTU,Emissions CO Lbs/MMBTU,Emissions VOCs Lbs/MMBTU,Damping Ratio,Inertia MJ/MW,Base MVA,Transformer X p.u.,Unit X p.u.,Pump Load MW,Storage Roundtrip Efficiency
0,101_CT_1,101,1,U20,CT,Oil CT,Oil,8.0,4.96,1.0468,...,0.004,0.11,0.040,0,2.8,24.0,0.13,0.32,0,0
1,101_CT_2,101,2,U20,CT,Oil CT,Oil,8.0,4.96,1.0468,...,0.004,0.11,0.040,0,2.8,24.0,0.13,0.32,0,0
2,101_STEAM_3,101,3,U76,STEAM,Coal,Coal,76.0,0.14,1.0468,...,0.004,0.02,0.003,0,3.0,89.0,0.13,0.30,0,0
3,101_STEAM_4,101,4,U76,STEAM,Coal,Coal,76.0,0.14,1.0468,...,0.004,0.02,0.003,0,3.0,89.0,0.13,0.30,0,0
4,102_CT_1,102,1,U20,CT,Oil CT,Oil,8.0,4.88,1.0467,...,0.004,0.11,0.040,0,2.8,24.0,0.13,0.32,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,321_CC_1,321,1,U355,CC,Gas CC,NG,355.0,-3.34,1.0500,...,0.000,0.00,0.000,0,5.0,414.0,0.13,0.30,0,0
68,322_CT_5,322,5,U55,CT,Gas CT,NG,55.0,-9.73,1.0500,...,0.000,0.00,0.000,0,2.8,64.0,0.13,0.32,0,0
69,322_CT_6,322,6,U55,CT,Gas CT,NG,55.0,-9.73,1.0500,...,0.000,0.00,0.000,0,2.8,64.0,0.13,0.32,0,0
70,323_CC_1,323,1,U355,CC,Gas CC,NG,355.0,37.41,1.0500,...,0.000,0.00,0.000,0,5.0,414.0,0.13,0.30,0,0
71,323_CC_2,323,2,U355,CC,Gas CC,NG,355.0,37.41,1.0500,...,0.000,0.00,0.000,0,5.0,414.0,0.13,0.30,0,0

In [26]:
df_renew

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,Category,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Emissions N2O Lbs/MMBTU,Emissions CO Lbs/MMBTU,Emissions VOCs Lbs/MMBTU,Damping Ratio,Inertia MJ/MW,Base MVA,Transformer X p.u.,Unit X p.u.,Pump Load MW,Storage Roundtrip Efficiency
74,122_HYDRO_1,122,1,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
75,122_HYDRO_2,122,2,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
76,122_HYDRO_3,122,3,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
77,122_HYDRO_4,122,4,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
78,122_HYDRO_5,122,5,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,213_RTPV_1,213,1,RTPV,RTPV,Solar RTPV,Solar,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,13.2,0.0,0.00,0,0
153,309_WIND_1,309,1,WIND,WIND,Wind,Wind,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,148.3,0.0,0.00,0,0
154,317_WIND_1,317,1,WIND,WIND,Wind,Wind,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,799.1,0.0,0.00,0,0
155,303_WIND_1,303,1,WIND,WIND,Wind,Wind,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,847.0,0.0,0.00,0,0
156,122_WIND_1,122,1,WIND,WIND,Wind,Wind,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,713.5,0.0,0.00,0,0

In [27]:
df_special

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,Category,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Emissions N2O Lbs/MMBTU,Emissions CO Lbs/MMBTU,Emissions VOCs Lbs/MMBTU,Damping Ratio,Inertia MJ/MW,Base MVA,Transformer X p.u.,Unit X p.u.,Pump Load MW,Storage Roundtrip Efficiency
73,121_NUCLEAR_1,121,1,U400,NUCLEAR,Nuclear,Nuclear,400.0,-21.87,1.05,...,0.0,0.0,0.0,0,5.0,471.0,0.15,0.4,0,0
116,212_CSP_1,212,1,CSP,CSP,CSP,Solar,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,200.0,0.00,0.0,0,0

## calculate cost for the start up with different suitations

In [28]:
for idx, row in df_fossil.iterrows():
    fuel_price = row['Fuel Price $/MMBTU']
    cold_start_energy = row['Start Heat Cold MBTU']
    warm_start_energy = row['Start Heat Warm MBTU']
    hot_start_energy = row['Start Heat Hot MBTU']
    cold_start_cost = fuel_price * cold_start_energy
    warm_start_cost = fuel_price * warm_start_energy
    hot_start_cost =  fuel_price * hot_start_energy

In [29]:
# generate a dictionary contains fossil generator information
fossil_dict = {}
for idx, row in df_fossil.iterrows():
    gen_name = row['GEN UID']
    gen_dict = {}
    gen_dict['name'] = gen_name
    bus_id= row['Bus ID']
    gen_dict['bus_name'] = df_bus[df_bus["Bus ID"]==bus_id]["Bus Name"].to_list()[0]
    gen_dict['gen_type'] = row['Unit Type']
    gen_dict['max_p'] = row['PMax MW']
    gen_dict['min_p'] = row['PMin MW']
    gen_dict['ramp'] = row['Ramp Rate MW/Min'] * 60 # ramp rate should be MW/hr
    gen_dict['fuel_p'] = row['Fuel Price $/MMBTU']
    gen_dict['min_down_time'] = int(np.round(row['Min Down Time Hr'], 0)) # should be rounded to an integer
    gen_dict['min_up_time'] = int(np.round(row['Min Up Time Hr'], 0)) # should be rounded to an integer
    gen_dict['start_up_time_hot'] = int(np.round(row['Start Time Hot Hr'], 0))
    gen_dict['start_up_time_warm'] = int(np.round(row['Start Time Warm Hr'], 0))
    gen_dict['start_up_time_cold'] = int(np.round(row['Start Time Cold Hr'], 0))
    gen_dict['start_heat_hot'] = row['Start Heat Hot MBTU']
    gen_dict['start_heat_warm'] = row['Start Heat Warm MBTU']
    gen_dict['start_heat_cold'] = row['Start Heat Cold MBTU']
    gen_dict['cost_curve'] = gen_param_dict[gen_name]
    
    fossil_dict[gen_name] = gen_dict

In [30]:
# generate a dictionary contains renewable generator information
renew_dict = {}
for idx, row in df_renew.iterrows():
    gen_name = row['GEN UID']
    gen_dict = {}
    gen_dict['name'] = gen_name
    gen_dict['gen_type'] = row['Unit Type']
    bus_id= row['Bus ID']
    gen_dict['bus_name'] = df_bus[df_bus["Bus ID"]==bus_id]["Bus Name"].to_list()[0]
    gen_dict['max_p'] = row['PMax MW']
#     gen_dict['min_p'] = row['PMin MW']
#     gen_dict['ramp'] = row['Ramp Rate MW/Min']
#     gen_dict['min_down_time'] = row['Min Down Time Hr']
#     gen_dict['min_up_time'] = row['Min Up Time Hr']
#     gen_dict['start_up_time_hot'] = row['Start Time Hot Hr']
#     gen_dict['start_up_time_cold'] = row['Start Time Cold Hr']
#     gen_dict['start_up_time_cold'] = row['Start Time Warm Hr']
    gen_dict['cost_curve'] = {'slope': 0, 'intercept': 0} # for the renewable generators, the operation cost is 0.
    
    renew_dict[gen_name] = gen_dict

In [31]:
 renew_dict["303_WIND_1"]

{'name': '303_WIND_1',
 'gen_type': 'WIND',
 'bus_name': 'Caesar',
 'max_p': 847.0,
 'cost_curve': {'slope': 0, 'intercept': 0}}

## Generator startup type check

In [32]:
# check the generator types to decide its startup types
def gen_startup_cost(type_gen_dict, gen_name):
#     min_down_time = type_gen_dict[gen_name]['min_down_time']
    hot_time = type_gen_dict[gen_name]['start_up_time_hot']
    warm_time = type_gen_dict[gen_name]['start_up_time_warm']
    cold_time = type_gen_dict[gen_name]['start_up_time_cold']
    fuel_p = type_gen_dict[gen_name]['fuel_p']
    start_heat_hot = type_gen_dict[gen_name]['start_heat_hot']
    start_heat_warm = type_gen_dict[gen_name]['start_heat_warm']
    start_heat_cold = type_gen_dict[gen_name]['start_heat_cold']
    
    start_up_cost_hot = start_heat_hot*fuel_p
    start_up_cost_warm = start_heat_warm*fuel_p
    start_up_cost_cold = start_heat_cold*fuel_p
    start_up_cost = {'hot': start_up_cost_hot, 'warm': start_up_cost_warm, 'cold': start_up_cost_cold}
    
    return start_up_cost

In [34]:
all_gen_dict = {}
all_gen_dict['fossil'] = fossil_dict
all_gen_dict['renew'] = renew_dict
# all_gen_dict['special'] = special_dict

gen_dict_path = os.path.join(os.getcwd(), '..', 'Data', 'gen_dict.json')

with open(gen_dict_path, "w") as f:
    json.dump(all_gen_dict, f)
    print("Successfully saved generator parameters to json files")

Successfully saved generator parameters to json files

In [90]:
fossil_dict['101_CT_1']

{'name': '101_CT_1',
 'fuel_p': 10.3494,
 'gen_type': 'CT',
 'max_p': 20.0,
 'min_p': 8,
 'ramp': 180.0,
 'min_down_time': 1.0,
 'min_up_time': 1.0,
 'start_up_time_hot': 0.0,
 'start_up_time_warm': 0.0,
 'start_up_time_cold': 1,
 'start_heat_hot': 5.0,
 'start_heat_warm': 5.0,
 'start_heat_cold': 5.0,
 'cost_curve': {'slope': 100.728, 'intercept': 272.4442528000002},
 'duration_type': 'C'}

## Test RHPTForecaster

In [1]:
from idaes.apps.grid_integration.forecaster import RHPTForecaster
import numpy as np

In [2]:
p = []
for i in range(10):
    p.append([i]*24)
price = np.array(p).reshape(-1)

scenario = 5
horizon = 36
planning_horizon = 24

In [3]:
forecaster = RHPTForecaster(price, scenario, horizon, planning_horizon)

pointer=0
forecaster._forecast_prices(pointer)

2025-07-02 15:48:13 [INFO] idaes.apps.grid_integration.forecaster: Number of periods from provided data is 10.
2025-07-02 15:48:13 [INFO] idaes.apps.grid_integration.forecaster: Number of scenarios is 5.
2025-07-02 15:48:13 [INFO] idaes.apps.grid_integration.forecaster: The length of the scenario is 36.

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
csv_path = "../Data/all_bus_lmp.csv"
df_lmp = pd.read_csv(csv_path)
lmp_arr = df_lmp['Abel_LMP'].to_numpy()
len(lmp_arr)

8784

In [8]:
forecaster = RHPTForecaster(lmp_arr, scenario, horizon, planning_horizon)

2025-07-02 15:48:25 [INFO] idaes.apps.grid_integration.forecaster: Number of periods from provided data is 366.
2025-07-02 15:48:25 [INFO] idaes.apps.grid_integration.forecaster: Number of scenarios is 5.
2025-07-02 15:48:25 [INFO] idaes.apps.grid_integration.forecaster: The length of the scenario is 36.

In [10]:
pointer = 7
lmp_forecasted = forecaster._forecast_prices(pointer)
for idx, l in enumerate(lmp_forecasted):
    actual_l = lmp_arr[(2+idx)*24: (2+idx)*24 + horizon]
    print(len(l), l- actual_l)

36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

## Test Rolling Horizon PT Results

In [2]:
from utils import read_rolling_horizon_params, check_optimal_status, calculate_total_profit,calculate_total_startup_shutdown
from Rolling_horizon.fossil_rolling_horizon_PT_parameter import gen_dict
from idaes.apps.grid_integration import RHPTForecaster

In [4]:
# read the results dictionary
json_path = os.path.join(os.getcwd(), "..", "Data", "test_366_gen_101_STEAM_3_result.json")
res_dict = read_rolling_horizon_params(json_path)

In [4]:
# check if all period problem converged to optimal
non_optimal = check_optimal_status(res_dict)
print(non_optimal)

[]

In [5]:
actual_profit = calculate_total_profit(res_dict)
ideal_profit = calculate_total_profit(res_dict, name="IdeaProfit")

print(f"PCM Profit: {17.63} M$")
print(f"Standard Profit: {19.11} M$.")
print(f"Ideal Profit: {np.round(ideal_profit/1e6, 2)} M$.")
print(f"Actual Profit: {np.round(actual_profit/1e6, 2)} M$.")

PCM Profit: 17.63 M$
Standard Profit: 19.11 M$.
Ideal Profit: 17.28 M$.
Actual Profit: 14.22 M$.

In [27]:
print("ideal", "actual")
for key in res_dict.keys():
    print(f"{np.round(res_dict[key]['IdeaProfit'], 2)}.", f"{np.round(res_dict[key]['ActualProfit'], 2)}.")

ideal actual
6236.44. -23544.4.
11888.46. 4400.1.
15582.73. -2490.63.
10249.28. 6191.78.
3415.52. -18961.42.
-3386.75. 3793.56.
7097.85. -6481.91.
-11558.45. -29750.33.
-3130.37. -15719.3.
0.0. 0.0.
-13499.95. -9562.88.
-14676.25. -13434.56.
-14709.48. -8615.19.
-12442.61. -19095.22.
-46.71. -10027.18.
117.24. -13811.83.
0.0. 0.0.
-12354.63. -9623.83.
-12537.97. -7397.53.
-11627.24. 3060.76.
4984.85. 177879.16.
44565.51. 1078.66.
46645.69. -20616.42.
43439.64. -16019.7.
34607.79. -19184.17.
31570.49. -11283.92.
-13440.15. -17391.65.
-15721.85. -17266.23.
-15858.04. -16590.77.
-16550.22. -16605.81.
-16982.1. -16640.85.
-16755.19. -17233.18.
155087.95. -16076.27.
169757.9. 125969.66.
234192.77. 24571.16.
241746.07. 170802.19.
282507.6. -2324.59.
104556.72. 9543.45.
106177.43. 13462.77.
45248.05. -4536.39.
39287.44. 765421.86.
156584.03. 180903.41.
193078.15. -2254.07.
190567.16. 4508.29.
188808.62. 1211.95.
189958.29. -1114.62.
36689.61. 5775.17.
2687.98. 632963.94.
129853.06. 219086.74.
191656.03. -6471.32.
190119.37. -21759.27.
186156.11. -17663.11.
181644.45. 16400.84.
58386.32. -16985.07.
0.0. 0.0.
-13220.89. -12337.47.
-12040.37. 116920.81.
64182.7. 296217.77.
121386.57. 11238.38.
128975.07. 316205.15.
192667.69. -23026.15.
187610.84. 311.18.
125121.94. -4537.82.
65942.82. 13904.65.
66254.42. 286859.2.
59499.54. 3165.66.
65505.74. 452663.72.
157144.76. 9399.45.
158285.61. -21417.59.
150667.51. 3254.16.
93619.9. -8807.14.
95884.89. -10487.29.
-14209.84. 10878.17.
190.03. -584.57.
3763.2. 151401.47.
33112.72. -10715.31.
32437.93. -7462.2.
31263.58. -15367.78.
24150.68. 382145.53.
126190.89. 418.31.
77890.23. -16301.11.
90633.95. 11140.6.
94305.46. 11614.86.
99644.34. 4207.07.
4565.67. 349.16.
4778.73. 769521.73.
160011.84. 13415.01.
160466.72. 22605.48.
162664.84. -4971.95.
160829.04. 446159.12.
249993.73. 185360.6.
132960.69. 13276.01.
132808.35. -17657.12.
125087.62. 43905.16.
136107.32. 13070.26.
49897.52. 9452.94.
14319.0. 7521.08.
13482.61. 7730.02.
19106.91. 2875.97.
10520.75. 5254.95.
8407.85. -7943.34.
4154.36. 40824.43.
10511.12. 462879.98.
101731.87. -9150.08.
98653.26. -7328.91.
96014.66. 15500.88.
100552.02. -13251.57.
97482.8. -6574.23.
-9948.55. -5238.28.
-7677.61. -23077.41.
-9731.62. -22319.98.
-14946.51. -10613.85.
-13841.63. 5720.96.
-8449.56. 1175.91.
-10810.59. 777542.89.
164741.2. 341145.36.
238582.34. 944371.89.
427370.65. 1058668.26.
633820.39. 484678.25.
727781.52. -15289.89.
565679.98. 8713.58.
497746.39. 426.69.
309821.85. 14855.79.
100532.78. -15740.14.
1222.29. 4106.51.
3738.18. 22731.68.
7517.62. -2793.84.
6767.69. -9531.2.
2046.11. 16317.02.
7767.99. 757153.25.
158625.41. -21196.27.
150257.97. -12741.83.
147543.71. 9898.74.
150667.14. -4453.8.
149507.99. 185.17.
-12619.6. -10133.1.
4400.55. 3146.77.
8797.8. -5002.76.
4277.21. 7231.87.
7886.97. 114.05.
5195.34. 2313.27.
5096.19. 21261.41.
7359.61. 44292.77.
17707.76. -3392.31.
14051.37. 5530.04.
14947.52. -11832.56.
12065.58. -21321.17.
3787.22. 33427.45.
2788.5. -9625.8.
1098.01. 90916.48.
39063.13. -5022.41.
40576.65. -29421.87.
39409.9. -25419.95.
27673.23. 151181.79.
60250.14. 190665.86.
61837.84. 5147.65.
62702.14. 23221.93.
72079.56. -8520.38.
75194.35. 18085.8.
49174.0. -5213.9.
7488.9. 36050.82.
13298.75. 7250.97.
9891.89. -11433.84.
9362.15. 14136.05.
8448.38. 20751.96.
13601.25. -1376.74.
6278.06. -2652.87.
4474.23. -1044.03.
6077.03. 5072.3.
4655.74. -14238.5.
455.92. -5573.98.
-14137.93. -14734.32.
-14402.21. -12543.43.
-10450.08. 302793.43.
62460.49. 8639.67.
66643.99. 22036.05.
74911.77. 12215.65.
78888.24. 8854.94.
75230.04. 4025.35.
12223.12. -0.48.
10095.19. 11803.3.
7711.33. 23719.73.
9892.64. -3575.07.
7431.11. 9900.61.
8750.08. 3350.53.
9162.97. 6788.7.
8189.7. 4346.57.
4362.3. 2755.93.
5805.91. -5071.56.
2826.43. 22649.76.
6768.22. 17342.28.
8939.88. 4080.41.
8714.42. 4863.16.
9173.98. 158191.08.
41551.44. 163624.39.
69700.29. 21887.78.
70561.72. 9370.81.
72052.48. 14133.21.
74042.42. 8505.23.
44523.89. 18819.78.
15421.84. 8481.88.
12588.79. 17385.6.
13573.68. 8575.55.
12401.28. 5293.42.
11711.25. 4975.15.
8942.32. 5485.55.
8343.06. 5638.08.
5993.55. 13537.26.
6985.89. 18748.72.
9676.95. 11209.05.
10923.73. 8731.91.
11573.0. 17273.31.
13900.05. 2196.46.
11631.89. 3042.56.
8490.66. -18388.63.
2573.34. 944.07.
1272.52. 502.39.
0.0. 0.0.
-12891.36. -7309.81.
0.0. 0.0.
-8367.47. -8642.12.
3029.68. -232.44.
2800.33. 11487.37.
4588.01. 22404.51.
8167.73. -2283.69.
7136.27. 4836.4.
7607.69. 1847.35.
7960.48. 2394.96.
6051.41. 6255.87.
2779.54. 9452.34.
5247.26. -2285.19.
3751.06. 15326.48.
6425.42. 7281.33.
7418.72. 2905.42.
6743.98. -1306.39.
4614.65. 2548.35.
5595.31. 15323.73.
5582.7. 34404.35.
11038.08. 10773.96.
12673.81. 10721.0.
15105.13. 3057.0.
15140.76. -2823.45.
11478.64. 2460.16.
5329.78. 11270.8.
5501.81. 3419.56.
4121.55. -13249.8.
1170.63. 7127.61.
2773.65. -2083.17.
1659.95. -177.38.
194.43. -5.83.
-12801.76. -8396.65.
1159.82. 2967.44.
323.89. 13859.83.
3527.79. 2077.81.
4121.14. 8830.18.
6966.4. 304.64.
6406.23. 1866.73.
5919.87. 2837.13.
3562.59. 174641.71.
38031.5. 10057.96.
38439.61. -11024.13.
35746.01. -7210.41.
34220.58. -25434.71.
29443.5. -8159.11.
726.24. 201.94.
-18059.91. 184518.11.
92999.82. -17752.57.
90869.85. -17254.87.
92505.82. 6829.3.
96339.63. -7102.0.
93055.84. -2706.93.
445.59. -62.78.
-13312.01. -9665.3.
1847.79. 5628.87.
1584.19. 1624.63.
2686.04. 1607.38.
3405.09. -2836.25.
2555.02. -4827.96.
962.01. -3593.84.
0.0. 0.0.
-8389.05. -12307.51.
2227.85. -8568.1.
907.08. 1061.88.
2086.34. -21174.05.
0.0. 0.0.
-13097.23. -11861.4.
-13250.45. -8464.78.
-12365.83. -11658.06.
-12943.12. -6981.99.
-9692.31. -6589.11.
-8578.24. -11898.64.
-8651.63. -21998.87.
-11502.46. -8399.09.
-10819.22. -7772.56.
-10814.77. -7929.25.
-14129.06. -25827.88.
-2103.83. 316.92.
3879.61. -3566.74.
1553.48. 6671.62.
2555.6. -5277.2.
1592.74. 2839.4.
-9126.99. -13503.87.
-9673.09. -16939.92.
-11295.89. -10472.75.
-11795.25. -20047.67.
9810.08. -24327.52.
19378.18. -7471.61.
20101.21. -387.86.
24688.91. 26015.64.
32989.77. 353238.97.
76686.76. 752061.84.
230085.07. -25505.04.
226911.28. -26255.38.
221233.69. -17.81.
215832.44. -14729.07.
146779.6. 4870.8.
-13351.03. -12778.79.
-15320.1. -14329.49.
-116.67. 942.97.
401.32. -21285.32.
3774.58. -10570.15.
-10561.54. -13949.97.
-10792.97. -17323.6.
-13364.83. -17723.85.
-16164.71. -10698.14.
-14706.21. -11903.03.
-8283.67. -10712.94.
6006.02. 4078.65.
6091.92. 20675.63.
14191.73. -19011.54.
9774.94. -14788.37.
8048.46. -13488.25.
-10205.88. -16575.74.
-11998.9. -6021.02.
-15401.67. -12596.72.
-14214.46. -17975.58.
-14188.16. -10137.11.
-12287.69. -12909.6.
-13631.21. 418317.72.
122493.9. 5012.09.
128481.65. 152012.63.
159088.24. 158997.79.
189704.37. -14446.82.
185936.13. 1697.47.
60702.3. 181501.58.
95952.53. 11694.69.
67888.94. -6641.57.
34761.07. 315518.43.
100754.12. -3196.73.
100377.95. -26261.78.
66531.14. -3890.6.
53323.83. 1327.1.
55433.03. 291164.68.
49136.33. -24726.24.
58159.71. -383.23.
63307.21. 2537.6.
66527.67. -4033.28.
63278.43. 40320.87.
6132.36. 3971.43.
9743.38. -6519.39.
8748.6. 19632.79.
12260.46. 13457.05.
15723.22. -14830.54.
4456.63. 24223.96.
8485.68. 38817.07.
17476.21. 19366.56.

In [28]:
for key in res_dict.keys():
    total_shutdown = sum(res_dict[key]["gen_101_STEAM_3"]["OperationVariables_shutdown"]["1"].values())
    total_startup = sum(res_dict[key]["gen_101_STEAM_3"]["OperationVariables_startup"]["1"].values())
    if total_shutdown > 0:
        print("shutdown", key)
    if total_startup > 0:
        print("startup", key)

startup period_0
shutdown period_6
startup period_7
shutdown period_9
shutdown period_10
startup period_10
shutdown period_11
startup period_11
shutdown period_12
startup period_12
startup period_13
shutdown period_16
shutdown period_17
startup period_17
shutdown period_18
startup period_18
startup period_19
shutdown period_25
shutdown period_26
startup period_26
shutdown period_27
startup period_27
shutdown period_28
startup period_28
shutdown period_29
startup period_29
shutdown period_30
startup period_30
shutdown period_31
startup period_31
startup period_32
shutdown period_54
shutdown period_55
startup period_55
startup period_56
shutdown period_71
startup period_72
shutdown period_79
startup period_80
shutdown period_107
shutdown period_108
startup period_108
shutdown period_109
startup period_109
shutdown period_110
startup period_110
shutdown period_111
startup period_111
shutdown period_112
startup period_112
shutdown period_113
startup period_113
startup period_114
shutdown period_134
startup period_135
shutdown period_170
shutdown period_171
startup period_171
shutdown period_172
startup period_172
startup period_173
shutdown period_217
startup period_218
shutdown period_219
startup period_220
shutdown period_249
startup period_250
shutdown period_264
startup period_265
shutdown period_271
startup period_272
shutdown period_279
startup period_280
shutdown period_284
shutdown period_285
startup period_285
shutdown period_286
startup period_286
shutdown period_287
startup period_287
shutdown period_288
startup period_288
shutdown period_289
startup period_289
shutdown period_290
startup period_290
shutdown period_291
startup period_291
shutdown period_292
startup period_292
shutdown period_293
startup period_293
shutdown period_294
startup period_294
startup period_295
shutdown period_300
shutdown period_301
startup period_301
shutdown period_302
startup period_302
shutdown period_303
startup period_303
shutdown period_304
startup period_304
startup period_305
shutdown period_315
shutdown period_316
startup period_316
startup period_317
shutdown period_320
shutdown period_321
startup period_321
shutdown period_322
startup period_322
shutdown period_323
startup period_323
shutdown period_324
startup period_324
shutdown period_325
startup period_325
startup period_326
shutdown period_331
shutdown period_332
startup period_332
shutdown period_333
startup period_333
shutdown period_334
startup period_334
shutdown period_335
startup period_335
shutdown period_336
startup period_336
shutdown period_337
startup period_337
startup period_338
shutdown period_350
shutdown period_351
startup period_351
shutdown period_352
startup period_352
startup period_353

In [29]:
calculate_total_startup_shutdown(res_dict, gen_name="gen_101_STEAM_3")

(71.0, 70.0)

In [22]:
slope = 16.466, 
intercept = 331.4380855711627

lmp_path = os.path.join("..", "Data", "all_bus_lmp.csv")
df_lmp = pd.read_csv(lmp_path)
lmp_data = df_lmp[gen_dict["gen_101_STEAM_3"]["bus_name"]+"_LMP"].to_numpy()

forecaster = RHPTForecaster(price_signal=lmp_data,
                            scenario=5,
                            horizon=36,
                            planning_horizon=24)

elec_rev = 0
cost = 0
pointer = 0

for i in res_dict:
    power =  res_dict[i]['gen_101_STEAM_3']['OperationVariables_power']['1']
    op_mode = res_dict[i]['gen_101_STEAM_3']['OperationVariables_op_mode']['1']
    power_arr = np.array([v for v in power.values()])
    op_mode_arr = np.array([v for v in op_mode.values()])
    lmp = forecaster.fetch_original_signal(pointer)
    cost += sum(power_arr * slope + op_mode_arr * intercept)
    elec_rev += sum(lmp*power_arr)
    pointer += 1
    
cost += 71*5284.8*2.11399

elec_rev, cost, elec_rev-cost

2025-08-08 17:22:25 [INFO] idaes.apps.grid_integration.forecaster: Number of periods from provided data is 366.
2025-08-08 17:22:25 [INFO] idaes.apps.grid_integration.forecaster: Number of scenarios is 5.
2025-08-08 17:22:25 [INFO] idaes.apps.grid_integration.forecaster: The length of the scenario is 36.

(25360640.22043799, 11141318.534188543, 14219321.686249446)

## Using new LMP

### PCM

In [32]:
df_lmp = pd.read_csv("Bus_LMP.csv")
df_dispatch = pd.read_csv("Generator_Dispatch.csv")

state_arr = df_dispatch["101_STEAM_3_Unit State"].to_numpy()

int_state_arr = []
for i in state_arr:
    if i:
        int_state_arr.append(1)
    else:
        int_state_arr.append(0)
int_state_arr = np.array(int_state_arr)

startups = 0
for i in range(1, len(state_arr)):
    if int(state_arr[i]) - int(state_arr[i-1]) == 1:
        startups += 1
        
dispatch_arr = df_dispatch["101_STEAM_3_Dispatch"].to_numpy()

costs = dispatch_arr * 16.466 + 331.4381*int_state_arr
sum(costs) + 2.11399*5284.8*6

# sum(df_lmp["Abel_LMP"].to_numpy() * dispatch_arr)

12467569.950188339

### Determinstic PT

In [33]:
js_path = "../Data/det_fossil_PT_fixed_dispatch_results.json"

with open(js_path, "r") as f:
    res_dict = json.load(f)

startup = 0
rev = 0
vom = 0
for i in range(1, 366*24):
    startup += res_dict[str(i)]['startup']
    rev += res_dict[str(i)]['rev']
    vom += res_dict[str(i)]['vom']
    
startup, rev, vom + 2.11399*5284.8*6

(7.0, 29073470.33426585, 12465986.972160637)